(function(m){var window=this;var ZA=function(a){if(!a.length)return 0;var b=a[0],c=b.offsetHeight;1<a.length&&(c=a[1].offsetTop-b.offsetTop);return c};var $A=function(a,b){if(!b)return[];var c=(0,m.K)((0,m.W)(a,"scroll-unit"),b);if(0>=c.length)return[];var d=b.scrollTop,e=ZA(c),g=b.offsetHeight,h=Math.max(Math.floor(d/e),0),d=Math.min(Math.ceil((d+g)/e),c.length);return(0,m.na)((0,m.Pc)(c),h,d)};var aB=function(a,b){var c=(0,m.J)(b);if(c){var d=(0,m.W)(a,"toggled"),c=(0,m.K)(d,c);(0,m.z)(c,function(a){(0,m.pf)(a,d)})}};
var bB=function(a){var b=(0,m.L)("related-video",a),b={video_id:(0,m.F)(b,"video-id"),action_dismiss_video_recommendation:1},b=(0,m.Te)("/related_ajax",b);window.spf.load(b,{method:"POST",onSuccess:function(){m.T.hide(a)}})};var cB=function(a){var b=a.currentTarget.href,c=(0,m.Qq)();if(c){var d=(0,m.$e)(b).v;(0,m.t)("VIDEO_ID")==d&&(c=Math.floor(c.getCurrentTime()),a.currentTarget.href=(0,m.Te)(b,{t:c}))}};
var dB=function(a){a.stopPropagation();a=a.currentTarget;var b=(0,m.P)(a,"video-list-item");if(b)switch((0,m.F)(a,"action")){case "hide":bB(b)}};
var eB=function(){var a=m.Hq?(0,m.L)("appbar-playlist-card"):fB,b=(0,m.L)(gB,a);if(b&&(0,m.ke)(b)){var c=m.Cn.getInstance();if(a&&b){var d=(0,m.K)((0,m.W)(c,"scroll-unit"),a),b=(0,m.ka)(d,b);if(0<=b&&a&&!((0,window.isNaN)(b)||0>b)&&(c=(0,m.K)((0,m.W)(c,"scroll-unit"),a),!(0>=c.length))){b>=c.length&&(b=c.length-1);var d=ZA(c),e=a.offsetHeight,g=Math.max(Math.floor(a.scrollTop/d),0);b>g-1&&(d=Math.floor(e/d),e=c.length,b+d>e&&(b=e-d+1));0>b&&(b=0);b=c[b].offsetTop;a&&!(0,window.isNaN)(b)&&(0>b&&(b=
0),a.scrollTop=b,(0,m.uc)(a,"scroller-offset",b+""),(0,m.Bn)(a))}}}};var hB=function(a,b){var c=null;(0,m.z)(a,function(a){(0,m.rf)(a,gB)&&(c=a)});if(c){var d=(0,m.je)(c);d||(d=a[0]);var e=(0,m.ke)(c);e||(e=a[a.length-1]);var g=m.Eq,h=iB;g&&d&&(d={v:(0,m.F)(d,"video-id")},b?d.shuffle=b:-1!=g.href.indexOf("shuffle=")&&(d.shuffle=0),g.href=(0,m.cf)(g.href,d));h&&e&&(d={v:(0,m.F)(e,"video-id")},b?d.shuffle=b:-1!=h.href.indexOf("shuffle=")&&(d.shuffle=0),h.href=(0,m.cf)(h.href,d))}};
var jB=function(a){var b=(0,m.t)("SHUFFLE_VALUE");if(!b){var c=0;(0,m.z)(a,function(a){(0,m.rf)(a,gB)&&(c=(0,m.F)(a,"index"))});b=(c<<8)+Math.floor(256*Math.random());(0,m.qa)("SHUFFLE_VALUE",b)}return b};var kB=function(a){(0,m.$b)(a,function(a,c){var d=(0,window.parseInt)((0,m.F)(a,"index"),10),e=(0,window.parseInt)((0,m.F)(c,"index"),10);return d-e});return a};
var lB=function(a,b){function c(a){var c=0,d=[];for(a=a.split("");a.length;){var c=(b+c)%a.length,e=a[c];(0,m.la)(a,c);d.push(e)}return d.join("")}(0,m.$b)(a,function(a,b){var d=(0,m.F)(a,"video-id"),e=(0,m.F)(b,"video-id");return c(d).localeCompare(c(e))});var d=b>>8,e=(0,m.Jb)(a,function(a){a=(0,m.F)(a,"index");return d==a})||0;0<e&&(a=(0,m.na)(a,e).concat((0,m.na)(a,0,e)));return a};
var mB=function(a,b,c){var d=a.currentTarget.href;b=b||"BFa";var e={},g=(0,m.t)("SHUFFLE_VALUE");g?e.shuffle=g:-1!=d.indexOf("shuffle=")&&(e.shuffle=0);e&&(d=(0,m.cf)(d,e));a.currentTarget.href=d;(0,m.Fq)(d,b,c)};var nB=function(){(0,m.B)("watch-list-change")};var oB=function(a){"NEAR_END"==a.slice(0,-1)&&((0,m.Iq)(),a=(0,window.parseInt)(a.slice(-1),10),(0,m.Lq)(a))};var pB=function(){var a=$A(m.Cn.getInstance(),fB);(0,m.z)(a,function(a){(0,m.rq)(a)})};
var qB=function(){var a=(0,m.K)("related-video-featured");(0,m.z)(a,function(a){m.T.show(a)})};var rB=function(){m.Cq=!0};var sB=function(){var a=iB;(0,m.Fq)(a.href,"keys");(0,m.mo)(a.href)};var tB=function(){(0,m.Aq)("keys")};var uB=function(a){switch(a){case 5:(0,m.Gq)(5,"html5_ns")}};var vB=function(a){0==a&&(0,m.Aq)("autoplay",!0);m.Nq&&(2==a?(0,m.Q)(m.Pq,"paused"):1==a&&(0,m.pf)(m.Pq,"paused"))};
var wB=function(a){var b=m.Dq,c=(0,m.ye)(a.currentTarget,"li");if(b&&c){var d=fB;(0,m.Q)(d,"playlist-editing-locked");a=(0,m.F)(b,"full-list-id");var b=(0,m.F)(c,"video-id"),e=(0,m.F)(c,"index");(0,m.V)("/addto_ajax?action_delete_from_playlist=1",{format:"XML",method:"POST",ga:{video_ids:b,session_token:(0,m.Lc)("addto_ajax")||"",full_list_id:a,index:e-1},onSuccess:function(){(0,m.M)(c);var a=(0,m.Id)("li",null,d),b=1,e=0;(0,m.z)(a,function(a){if(!m.Hq)if((0,m.rf)(a,gB))e=b;else{var c=(0,m.Id)("span",
"count",a);c&&c[0]&&(c[0].innerHTML=b)}(0,m.uc)(a,"index",b);b+=1});m.Hq||((0,m.J)("watch7-playlist-current-index").innerHTML=e,(0,m.J)("watch7-playlist-length").innerHTML=b-1);hB(a,(0,m.t)("SHUFFLE_VALUE"))},Ba:function(){(0,m.pf)(d,"playlist-editing-locked");nB()}})}};var xB=function(a,b){var c=(0,m.F)(a.currentTarget,"clicktracking")||"";mB(a,b,c)};var yB=function(a){var b=(0,m.ye)(a.currentTarget,"li"),b=(0,m.F)(b,"clicktracking")||"";mB(a,void 0,b)};
var zB=function(){if(m.Hq){var a=(0,m.vl)(m.el.getInstance(),AB);(0,m.of)(m.Pq,"watch-playlist-collapsed",a)}else(0,m.qf)((0,m.J)("player"),"watch-playlist-collapsed")||(a=(0,m.Zp)((0,m.J)("watch7-playlist-tray-container")),(0,m.u)(pB,a))};
var BB=function(){var a=fB,b=(0,m.Pc)(a.getElementsByTagName("li"));if((0,m.vl)(m.el.getInstance(),CB))b=kB(b),(0,m.qa)("SHUFFLE_VALUE",0);else var c=jB(b),b=lB(b,c);(0,m.ae)(a);(0,m.z)(b,function(b){a.appendChild(b)});c=(0,m.t)("SHUFFLE_VALUE");hB(b,c);eB();pB();nB()};var DB=function(){var a=(0,m.t)("PLAYER_REFERENCE");a&&a.getPlayerState?1==a.getPlayerState()?a.pauseVideo():a.playVideo():((0,m.qf)(m.Pq,"paused"),m.Jq=!m.Jq)};
var EB=function(){var a=(0,m.vl)(m.el.getInstance(),m.Bq),b=m.bh.getInstance();(0,m.hh)(76,a);b.save();(0,m.qa)("LIST_AUTO_PLAY_ON",!a)};var FB=function(){var a=m.Dq;return!(!a||"False"==(0,m.F)(a,"shareable"))};var GB=function(a){var b=(0,m.t)("LIST_END_TIME");b||(b=a.getDuration());for(var c=5;0<c;c--)a.addCueRange("NEAR_END"+c,b-c,b-c+1);a.addEventListener("onCueRangeEnter",oB)};
var HB=function(a){if(!a.metaKey&&!a.ctrlKey){var b=a.target;if("INPUT"!=b.tagName&&"TEXTAREA"!=b.tagName&&"SELECT"!=b.tagName&&"EMBED"!=b.tagName)switch(a.keyCode){case 78:a.shiftKey&&(0,m.B)("player-shortcut-next");break;case 80:a.shiftKey&&(0,m.B)("player-shortcut-prev");break;case 106:(0,m.B)("player-shortcut-rewind");break;case 108:(0,m.B)("player-shortcut-fast-forward");break;case 107:(0,m.B)("player-shortcut-play-pause")}}};var IB=function(a,b){return"videos"==a?JSON.parse(b):b};
var JB=function(a){var b=window.location.href;b.indexOf("#")==b.length-1&&m.Qd&&(window.location.hash="#!");var b=window.document.body,c=(0,m.Dd)(b),d=[];d.push("<!DOCTYPE html>");d.push("<html><head>",a,"</head><body>","","</body></html>");a=(0,m.Wt)(c,"display: none");b.appendChild(a);b=d.join("");d=a.contentDocument||a.contentWindow.document;d.open();d.write(b);d.close();m.Ex=a};
var KB=function(){var a=(0,m.K)("related-video-featured");2==a.length?(0,m.kd)(a[0],"related-video-featured-booster")?m.T.show(a[1]):m.T.show(a[0]):(0,m.z)(a,function(a){m.T.show(a)})};var LB=function(a){0==a.length?qB():(0,m.Fx)("watch_related",a[0],null,function(a,c){var d=c.html_content||"",e=(0,m.J)(window.pyv_related_box_id||"watch-related");e&&(0!=e.innerHTML.indexOf(d)&&e.insertBefore((0,m.Zd)(d),e.firstChild),(d=(0,m.J)("pyv-watch-related-dest-url"))&&d.setAttribute("href",m.Gx),(0,m.Na)(m.Hx))})};
var MB=function(a){var b=(0,m.Te)("/related_ajax",{video_id:(0,m.t)("VIDEO_ID"),action_more_related_videos:1});window.spf.load(b,{onSuccess:a})};var NB=function(a){"true"!=(0,m.F)(a,"loaded")&&((0,m.uc)(a,"loaded","true"),(0,m.V)("/watch_ajax",{format:"XML",ha:{action_get_video_attributions_component:1,v:(0,m.t)("VIDEO_ID")},onSuccess:function(b,c){a.innerHTML=c.html_content}}))};
var OB=function(a){(0,m.V)("/insight_ajax",{format:"XML",method:"POST",ha:{action_get_statistics_and_data:1,v:(0,m.t)("VIDEO_ID")},ga:{session_token:(0,m.Lc)("insight_ajax")},onSuccess:function(b,c){a(c.html_content,c.graph_data,!0)},onError:function(){a(null,null,!1)}})};
var PB=function(a){var b=0,c=(0,m.Qq)();c&&c.pauseVideo&&(c.pauseVideo(),b=c.getCurrentTime());b=Math.floor(b);c=Math.floor(b/60);(0,m.V)("/watch_ajax",{method:"GET",ha:{action_get_report_video_component:1,video_id:(0,m.t)("VIDEO_ID"),t_mins:c,t_secs:b-60*c},onSuccess:function(b,c){a(c.report_html,!0)},onError:function(){a(null,!1)}})};var QB=function(){var a=null;if(FB()){var b=(0,m.J)("share-with-playlist");if(!b||b&&b.checked)a=(a=m.Dq)?(0,m.F)(a,"full-list-id"):""}return a};
var RB=function(){var a=(0,m.L)("yt-uix-button-toggled",(0,m.J)("action-panel-share"));return FB()&&a?(0,m.F)(a,"video-id"):(0,m.t)("VIDEO_ID")};
var SB=function(){(0,m.rf)(window.document.body,"exp-top-guide")?(m.Hq=!0,m.Pq=(0,m.J)("watch-appbar-playlist"),fB=(0,m.L)("playlist-videos-list",m.Pq),m.Bq=(0,m.L)("toggle-autoplay",m.Pq),CB=(0,m.L)("shuffle-playlist",m.Pq),AB=(0,m.L)("toggle-menu-visibility",m.Pq),m.Eq=(0,m.L)("next-playlist-list-item",m.Pq),iB=(0,m.L)("prev-playlist-list-item",m.Pq),m.Dq=(0,m.L)("playlist-info",m.Pq),gB="currently-playing"):(m.Hq=!1,m.Pq=(0,m.J)("playlist"),fB=(0,m.J)("watch7-playlist-tray"),m.Bq=(0,m.J)("watch7-playlist-bar-autoplay-button"),
CB=(0,m.J)("watch7-playlist-bar-shuffle-button"),AB=(0,m.J)("watch7-playlist-bar-toggle-button"),m.Eq=(0,m.J)("watch7-playlist-bar-next-button"),iB=(0,m.J)("watch7-playlist-bar-prev-button"),m.Dq=(0,m.J)("watch7-playlist-data"),gB="playlist-bar-item-playing");if(m.Pq&&fB){if(!m.Hq){TB.push((0,m.R)((0,m.J)("watch7-playlist-scrollfloater-autoplay-toggle"),"click",DB));m.Oq=m.T.Oj((0,m.J)("watch7-content")).y;UB.push((0,m.x)("page-scroll",m.Mq));var a=(0,m.Qq)();a&&a.addEventListener("onReady",GB)}TB.push((0,m.R)(m.Bq,
"click",EB));TB.push((0,m.R)(CB,"click",BB));TB.push((0,m.R)(AB,"click",zB));TB.push((0,m.R)(m.Eq,"click",function(a){xB(a,"bf_next")}));TB.push((0,m.R)(iB,"click",function(a){xB(a,"bf_prev")}));TB.push((0,m.Qf)(fB,"click",yB,"a"));TB.push((0,m.Sf)(fB,"click",wB,"yt-uix-button-playlist-remove-item"));UB.push((0,m.x)("navigate",rB));UB.push((0,m.x)("player-state-change",vB));UB.push((0,m.x)("player-error",uB));UB.push((0,m.x)("player-shortcut-next",tB));UB.push((0,m.x)("player-shortcut-prev",sB));
(0,m.t)("SKIP_TO_NEXT_VIDEO")&&(0,m.Gq)(5);eB();pB();nB()}};m.VB=function(a,b){var c=a.type;if((0,m.rc)(c))switch(c.toLowerCase()){case "checkbox":case "radio":a.checked=b?"checked":null;break;case "select-one":a.selectedIndex=-1;if((0,m.n)(b))for(var d=0;c=a.options[d];d++)if(c.value==b){c.selected=!0;break}break;case "select-multiple":c=b;(0,m.n)(c)&&(c=[c]);for(var e=0;d=a.options[e];e++)if(d.selected=!1,c)for(var g,h=0;g=c[h];h++)d.value==g&&(d.selected=!0);break;default:a.value=null!=b?b:""}};
var WB=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var g=arguments[e];if(c>=g.length)return b;d.push(g[c])}b.push(d)}};var XB=function(){this.b=new m.Du(this);this.k=!1};
var YB=function(){if((0,m.t)("WATCH_LEGAL_TEXT_ENABLE_AUTOSCROLL")){var a=window.document.getElementById("watch_companion_legal_text");a&&(ZB=new XB,ZB.start(a))}var b=(0,m.t)("ADS_DATA");if(b){$B(b);aC=b;bC=(0,m.Qq)();null!=bC&&(bC.addEventListener("onApiChange",cC),bC.addEventListener("onReady",dC));null==window.adModuleLoaded&&(b.fetch_ads_in_page||b.fetch_ads_fallback_in_page)&&(a=(0,m.l)("ytplayer.config"),a=(0,m.vb)(a),a.args.allow_html5_ads||(eC=!0,(0,m.Ka)("//s0.2mdn.net/instream/html5/ima3.js",
fC)));(0,m.t)("WATCH_RELATED_DELAY")||gC();b.use_gut&&(window.spf.scripts.unload("//www.googletagservices.com/tag/js/gpt.js"),(0,m.Ka)("//www.googletagservices.com/tag/js/gpt.js",function(){hC(b.gut_vars.tag)}));if(b.show_afv||b.show_afc)window.spf.scripts.unload("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),(0,m.Ka)("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),(0,m.Ka)("//www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22ads%22%2C%22version%22%3A%221%22%2C%22callback%22%3A%22(function()%7B%7D)%22%2C%22packages%22%3A%5B%22content%22%5D%7D%5D%7D");
b.show_afc&&iC(b);jC()}};var gC=function(){var a=(0,m.t)("ADS_DATA");a&&(a.show_pyv?JB("<script>var pyvOptions = "+a.pyv_vars.iframe_json+'; for (var key in pyvOptions) { window[key] = pyvOptions[key]; } window["google_ad_request_done"] = parent.yt.www.ads.pyv.pyvWatchAfcWithPpvCallback; \x3c/script><script src="//pagead2.googlesyndication.com/pagead/show_ads.js">\x3c/script>'):qB())};var jC=function(){kC()&&bC.getOption("ad","PAGE_JAVASCRIPT_INITIALIZED",{})};
var $B=function(a){lC=[];if("afv_vars"in a)for(var b in a.afv_vars)window[b]=a.afv_vars[b],lC.push(b)};var hC=function(a){"googletag"in window&&(mC=window.googletag.defineSlot(a,[[300,250],[300,60]],"yt-gut-content"))&&(mC.set("ad_type","flash"),mC.addService(window.googletag.companionAds()),window.googletag.enableServices(),a=mC.getSizes(),nC=a[0],oC=a[1])};
var pC=function(a,b){a||(a="");b||(b=!1);var c=(0,m.J)("watch-channel-brand-div");c&&(0,m.ld)(c,"collapsible",b);if(c=(0,m.J)("google_companion_ad_div"))c.innerHTML=a;qC()};var rC=function(a,b){var c=Math.round(1E4*Math.random());return['<iframe src="',a,'" name="ifr_300x',b,"ad",c,'" id="ifr_300x',b,"ad",c,'" width="300" height="',b,'" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join("")};var sC=function(a){return!!a.match("/subscribe_widget.*render=video_wall_companion")};
var tC=function(a){a=a.replace(";dc_seed=",";kmyd=watch-channel-brand-div;dc_seed=");var b=rC(a,250);a=sC(a);pC(b,a)};var uC=function(a){a=a.replace(";dc_seed=",";kmyd=watch-longform-ad;dc_seed=");var b=rC(a,60);a=sC(a);pC(b,a)};
var vC=function(a,b){var c=250;"video"==a&&(c=60);var d=(0,window.decodeURIComponent)(b);pC(['<iframe name="fw_ad" id="fw_ad" ','width="300" height="'+c+'" ','marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join(""));var e=(0,m.J)("fw_ad");if(e){var e=e.contentWindow?e.contentWindow:e.contentDocument.document?e.contentDocument.document:e.contentDocument,g=window.navigator.userAgent.toLowerCase(),c=-1!=g.indexOf("msie"),g=-1!=g.indexOf("opera");e.document.open();
e.document.write(d);c||g?(0,m.u)(function(){e.document.close()},7500):e.document.close()}};var qC=function(){(0,m.B)("watchads-adLoad")};var wC=function(){window.google_ad_output="html";window.google_ad_height="250";window.google_ad_format="300x250_as";window.google_container_id="google_companion_ad_div"};
var xC=function(){var a=window.document.getElementById("google_companion_ad_div");if(a&&(a=a.firstElementChild))try{a.contentWindow.postMessage((0,window.encodeURIComponent)(yC)+","+(0,window.encodeURIComponent)(zC),"*")}catch(b){}};var AC=function(){var a=window.document.getElementById("movie_player");a&&a.pauseVideo()};var BC=function(){};var CC=function(){qC()};
var iC=function(a){if(!DC){if(!a){if(!aC)return;a=aC}var b=(0,m.l)("google.ads.Ad");b?(DC=!0,new b(a.afv_vars.google_ad_client,"google_companion_ad_div",a.afc_vars)):EC=(0,m.u)(function(){iC(a)},200)}};var FC=function(){kC()&&GC&&(bC.getOption("ad","AD_VAR",{AD_VAST:HC}),IC())};var JC=function(){kC()&&KC&&bC.getOption("ad","AD_VAR",{AD_PREROLL_READY:!0})};var LC=function(){kC()&&MC&&bC.getOption("ad","AD_VAR",{AD_SDK_ERROR:!0})};
var kC=function(){var a;if(a=NC)if(a=null!=bC)if(a=null!=bC.getOptions)a=null!=bC.getOptions()&&(0,m.ac)(bC.getOptions(),"ad");return a};
var fC=function(){kC()&&bC.getOption("ad","AD_VAR",{JS_SDK_LOADED:!0});var a=(0,m.l)("ytplayer.config"),a=(0,m.vb)(a);if(a.args.ad_tag&&a.args.dclk){var b=new m.mw(a.args.ad_tag,a.args.mpu),c=0;a.args.instream&&(c|=1);a.args.trueview&&(c|=2);a.args.invideo&&(c|=4);a.args.mpu&&(c|=8);0<c&&(OC.push((0,m.nw)(b,c)),PC.push(a.args.instream||a.args.trueview));a.args.fetch_ads_fallback_in_page&&a.args.afv_ad_tag&&(b=a.args.afv_ad_tag,c={videoad_start_delay:0},a.args.aftv&&(c.video_format=18),OC.push((0,m.cf)(b,
c)),PC.push(a.args.aftv),a.args.ad_channel_code_overlay&&a.args.aftv&&a.args.afv&&!a.args.afv_merge_enabled&&(OC.push((0,m.cf)(b,{ad_type:"text_image_flash",channel:a.args.ad_channel_code_overlay})),PC.push(!1)))}QC()};
var QC=function(){if(!(0,m.Sc)(OC)){IC();RC||(RC=(0,m.Xd)("div"),null!=window.document.body&&window.document.body.appendChild(RC));var a=new window.google.ima.AdDisplayContainer(RC,null,null);SC=new window.google.ima.AdsLoader(a);TC=new m.Du;TC.listen(SC,window.google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED,UC);TC.listen(SC,window.google.ima.AdErrorEvent.Type.AD_ERROR,VC);if(!KC){var b=!1;(0,m.z)(PC,function(a){b|=a});b||(KC=!0,JC())}a=new window.google.ima.AdsRequest;a.adTagUrl=OC.shift();
PC.shift();a.linearAdSlotWidth=640;a.linearAdSlotHeight=355;a.nonLinearAdSlotWidth=640;a.nonLinearAdSlotHeight=100;SC.requestAds(a,null)}};var cC=function(){jC();eC&&(FC(),JC(),LC())};var dC=function(){NC=!0;jC()};
var UC=function(a){if(a&&a.getResponse())if(HC=(0,m.cc)(a.getResponse()),aC.fetch_ads_fallback_in_page){try{WC=a.getAdsManager({},null)}catch(b){XC();return}YC||(YC=new m.Du,YC.listen(WC,window.google.ima.AdEvent.Type.LOADED,ZC),YC.listen(WC,window.google.ima.AdErrorEvent.Type.AD_ERROR,XC));try{WC.init(640,360,window.google.ima.ViewMode.NORMAL)}catch(c){IC()}}else GC=!0,FC();else VC()};
var ZC=function(a){(a=a.getAd())?!a.isLinear()&&"rm"in a.getTraffickingParameters()&&"true"==a.getTraffickingParameters().rm?(WC.sendImpressionUrls(),IC(),QC()):(wC(),GC=!0,FC()):VC()};var XC=function(){IC();QC()};var IC=function(){HC=null;GC=!1;SC=null;TC&&(TC.removeAll(),TC=null);YC&&(YC.removeAll(),YC=null);WC&&(WC.destroy(),WC=null);RC&&((0,m.M)(RC),RC=null)};var VC=function(){(0,m.Sc)(OC)?(MC=!0,LC()):QC()};
var $C=function(){var a=(0,m.J)("facebook_token_refresh_iframe"),b=(0,m.t)("FACEBOOK_TOKEN_REFRESH_URL");a&&(0,m.ej)("facebook_token_refresh")!=b&&((0,m.bj)("facebook_token_refresh",b,3600),a.src=b)};var aD=function(){var a=(0,m.qm)();m.T.hide((0,m.L)("flag-comment-step1",a));m.T.show((0,m.L)("flag-comment-step2",a));m.T.hide((0,m.L)("flag-comment-step3",a))};
var bD=function(){var a=(0,m.qm)(),b=(0,m.L)("flag-comment-form",a),c=(0,m.L)("flag-comment-block-user-input",a),d=(0,m.L)("submit-flag-comment",a),e=(0,m.L)("flag-comment-error-msg",a);m.T.hide(e);c.disabled=!0;d.disabled=!0;(0,m.V)("/comment_servlet",{format:"XML",method:"POST",ha:{flag_comment:1},ga:(0,m.Ze)((0,m.Bj)(b)),onSuccess:function(b,c){c&&c.html_content?(m.T.hide((0,m.L)("flag-comment-step1",a)),m.T.hide((0,m.L)("flag-comment-step2",a)),m.T.show((0,m.L)("flag-comment-step3",a)),(0,m.L)("flag-comment-captcha-placeholder",
a).innerHTML=c.html_content):m.lm.getInstance().hide()},onError:function(a,b){var k=b&&b.error_message;if(k){var p=(0,m.L)("yt-alert-message",e);(0,m.qe)(p,k)}m.T.show(e);c.disabled=!1;d.disabled=!1}})};var cD=function(a){var b=(0,m.qm)(),c=(0,m.L)("abuse-type-placeholder",b);a=(0,m.ye)(a.currentTarget,"LABEL");(0,m.qe)(c,(0,m.te)(a));(0,m.L)("continue-flag-comment",b).disabled=!1};
var dD=function(a){var b;switch(a){case "PENDING":b=(0,m.G)("COMMENT_PENDING");break;case "BLOCKED":b=(0,m.G)("COMMENT_BLOCKED");break;case "EMAIL":b=(0,m.G)("COMMENT_ERROR_EMAIL");break;case "INLINE_CAPTCHAFAIL":b=(0,m.G)("COMMENT_CAPTCHAFAIL");break;case "SHOW_COUNTDOWN":b=(0,m.G)("SHOW_COUNTDOWN");break;case "FAILED_MAINTENANCE":b=(0,m.G)("COMMENT_FAILED_MAINTENANCE");break;case "FAILED_OWNER_LINKING":b=(0,m.G)("COMMENT_OWNER_LINKING");break;case "FAILED_HASLINK":b=(0,m.G)("FAILED_HASLINK");break;
case "FAILED_HASTAGS":b=(0,m.G)("FAILED_HASTAGS");break;case "FAILED_ASCIIART":b=(0,m.G)("FAILED_ASCIIART");break;case "FAILED_TOOSHORT":b=(0,m.G)("FAILED_TOOSHORT");break;case "FAILED_TOOLONG":b=(0,m.G)("FAILED_TOOLONG");break;case "FAILED_BADPARENT":b=(0,m.G)("FAILED_BADPARENT")}return b||null};
var eD=function(a,b,c){this.H=!!c;this.cb=a;this.Dr=(0,m.J)("all-comments");this.Bf=(0,m.xf)("button","post-button",a);this.Nc=(0,m.xf)("textarea",null,a);this.ng=null;this.b=(0,m.L)("comments-remaining",this.cb);this.G=(0,window.parseInt)((0,m.F)(this.b,"max-count"),10);this.mg=(0,m.L)("comments-post-message",this.cb);this.Br=(0,m.L)("yt-alert-content",this.mg);this.j=(0,m.L)("comments-threshold-countdown",this.cb);this.F=[];this.D=[];this.k=null;this.wz=!!(0,m.t)("COMMENTS_INVERTED");fD(this);gD(this,
this.Nc,"focus",this.$r);gD(this,this.Nc,"blur",this.OA);gD(this,this.cb,"submit",this.Yr);gD(this,this.Nc,"change",this.Zr);gD(this,this.Nc,"keyup",this.Zr);gD(this,this.Nc,"keydown",this.PA);b&&this.$r()};var gD=function(a,b,c,d){a.F.push((0,m.R)(b,c,(0,m.q)(d,a)))};var hD=function(a){a.ng&&(a.ng.innerHTML="")};var fD=function(a){var b=a.G-a.Nc.value.length;a.b.innerHTML=(0,m.Ic)("CHARACTERS_REMAINING",b);b=0>b;(0,m.ld)(a.b,"too-many",b);a.Bf.disabled=b};
var iD=function(a,b){var c=(0,m.q)(function(){0==b?((0,m.Jc)(d),jD(this)):(b--,this.j.innerHTML=(0,m.Ic)("SECONDS_REMAINING",b))},a);kD(a);var d=(0,m.Kc)(c,1E3);c();a.D.push(d)};var kD=function(a){m.T.hide(a.b);m.T.show(a.j);a.Bf.disabled=!0};var jD=function(a){m.T.hide(a.j);m.T.hide(a.mg);m.T.show(a.b);a.j.innerHTML="";a.Bf.disabled=!1};
var lD=function(a,b,c){var d=dD(b)||(0,m.G)("COMMENT_ERROR");a.Br.innerHTML=d;(0,m.jd)(a.mg,"yt-alert-info","yt-alert-error");m.T.show(a.mg);switch(b){case "INLINE_CAPTCHA":case "INLINE_CAPTCHAFAIL":(0,m.V)("/comment_servlet?gimme_captcha=1",{format:"XML",method:"POST",ga:{session_token:(0,m.Lc)("comment_servlet")},onSuccess:function(a,b){this.ng||(this.ng=window.document.createElement("div"),this.ng.className="comment-captcha",(0,m.ce)(this.ng,this.Nc));this.ng.innerHTML=b.html_content;this.Bf.disabled=
!1},W:a});break;case "SHOW_COUNTDOWN":iD(a,(0,window.parseInt)(c.countdown_timer,10)||30);break;default:a.Bf.disabled=!1,hD(a)}};var mD=function(a){this.da=a;this.Zs=(0,m.L)("yt-uix-pager-show-more");this.k=!!(0,m.t)("ENABLE_LIVE_COMMENTS");this.b=[];(a=(0,m.L)("comments-pagination",this.da))&&(0,m.F)(a,"ajax-enabled")&&this.b.push((0,m.Sf)(this.da,"click",(0,m.q)(this.D,this),"yt-uix-pager-button"))};
var nD=function(a,b){var c=(0,m.Id)("li","comment",void 0),c=(0,m.F)(c[c.length-1],"id"),d=a.Mj?!1:!0;m.T.show("comments-loading");oD(a,c,function(a,c){c.html_content&&(m.T.hide("comments-loading"),this.Mj=window.document.createElement("div"),this.Mj.innerHTML=c.html_content,!d&&0<(0,m.Id)("li","comment",this.Mj).length&&m.T.show(this.Zs),b&&b())})};
var oD=function(a,b,c){(0,m.V)("/watch_ajax?action_get_comments=1",{format:"XML",ha:{v:(0,m.t)("VIDEO_ID"),p:1,commentthreshold:(0,m.t)("COMMENTS_THRESHHOLD"),commenttype:"everything",enable_live_comments:a.k?"yes":null,last_comment_id:b,page_size:(0,m.t)("COMMENTS_PAGE_SIZE"),source:(0,m.t)("COMMENT_SOURCE")},onSuccess:c,W:a})};var pD=function(a,b,c){a=(0,m.ye)(a,"form");(0,m.sc)(a,"initialized")||((0,m.uc)(a,"initialized","true"),qD=new eD(a,!b,c),b&&qD.focus())};
var rD=function(a){a=a.currentTarget;var b=(0,m.ye)(a,null,"comment");switch((0,m.F)(a,"action")){case "approve":sD(b);break;case "block":(0,window.confirm)((0,m.G)("BLOCK_USER"))&&(tD(b,!0),(0,m.H)(b,"blocked"));break;case "unblock":tD(b,!1);(0,m.I)(b,"blocked");break;case "flag-in-place":if(uD(!1)){var c=(0,m.J)("comment-flag-area");a=(0,m.F)(b,"id");var d=(0,m.F)(b,"author-id"),e=(0,m.te)((0,m.L)("author",b)),b=(0,m.L)("comment-text",b).innerHTML,g=(0,m.t)("VIDEO_ID");m.lm.getInstance().show(c);
c=(0,m.qm)();(0,m.L)("flagged-comment-id",c).value=a;(0,m.L)("flagged-comment-author-id",c).value=d;(0,m.L)("flagged-comment-video-id",c).value=g;(0,m.qe)((0,m.L)("flagged-comment-author-name",c),e);(0,m.L)("flagged-comment-text",c).appendChild((0,m.Zd)(b));(0,m.R)((0,m.L)("continue-flag-comment",c),"click",aD);(0,m.Sf)(c,"click",bD,"submit-flag-comment");(0,m.Sf)(c,"click",cD,"abuse-type-radio-input")}break;case "flag":vD(b,"mark_comment_as_spam");break;case "flag-profile-pic":vD(b,"flag_profile_pic");
break;case "unflag":a=(0,m.F)(b,"id");(0,m.V)("/comment_servlet",{format:"XML",method:"POST",ga:{unmark_comment_as_spam:a,entity_id:(0,m.t)("VIDEO_ID"),session_token:(0,m.Lc)("comment_servlet")}});break;case "hide":(0,m.H)(b,"hidden");break;case "show":(0,m.I)(b,"hidden");break;case "remove":wD(b);break;case "reply":xD(b);break;case "realtime-reply":uD(!0)&&(qD||(a=(0,m.L)("comments-textarea",(0,m.J)("comments-view")),pD(a)),a=qD,a.reset(),a.focus());break;case "vote-up":yD(b,!0);break;case "vote-down":yD(b,
!1);break;case "show-parent":zD(b)}};var uD=function(a){return(0,m.t)("COMMENTS_SIGNIN_URL")?((0,m.lo)((0,m.t)("COMMENTS_SIGNIN_URL")),!1):a&&(0,m.t)("COMMENTS_CHANNEL_CREATE_URL")?((0,m.lo)((0,m.t)("COMMENTS_CHANNEL_CREATE_URL")),!1):(0,m.t)("COMMENTS_YPC_CAN_POST_OR_REACT_TO_COMMENT")?!0:!1};
var sD=function(a){var b=(0,m.F)(a,"id"),c=(0,m.t)("VIDEO_ID");(0,m.I)(a,"pending");(0,m.V)("/comment_servlet?field_approve_comment=1",{format:"XML",method:"POST",ga:{comment_id:b,entity_id:c,session_token:(0,m.Lc)("comment_servlet")},onError:function(){(0,m.H)(a,"pending")}})};
var tD=function(a,b){var c={};c["action_"+(b?"":"un")+"block_commenter"]=1;var d=(0,m.F)(a,"id");(0,m.V)("/link_ajax",{format:"XML",method:"POST",ha:c,ga:{session_token:(0,m.Lc)("link_ajax"),comment_id:d},onSuccess:function(a,b){b&&b.success_message&&window.alert(b.success_message)},onError:function(a,b){b&&b.error_message&&window.alert(b.error_message)}})};
var vD=function(a,b){if(uD(!1)){var c=(0,m.F)(a,"id"),d=(0,m.t)("VIDEO_ID");m.T.hide(a);(0,m.H)(a,"flagged");d={entity_id:d};d[b]=c;(0,m.V)("/comment_servlet",{format:"XML",method:"POST",ha:d,ga:{session_token:(0,m.Lc)("comment_servlet")},onError:function(){m.T.show(a);(0,m.I)(a,"flagged")}})}};
var wD=function(a){var b=(0,m.F)(a,"id"),c=(0,m.t)("VIDEO_ID");m.T.hide(a);(0,m.V)("/comment_servlet?remove_comment=1",{format:"XML",method:"POST",ga:{comment_id:b,entity_id:c,session_token:(0,m.Lc)("comment_servlet")},onError:function(){m.T.show(a)}})};
var xD=function(a){if(uD(!0))if((0,m.kd)(a,"replying"))(0,m.kd)(a,"replying")&&((0,m.I)(a,"replying"),a=(0,m.L)("comments-post-container",a),(0,m.M)(a));else{(0,m.H)(a,"replying");var b=(0,m.L)("comments-post",(0,m.J)("watch-discussion")||(0,m.J)("watch-discussion")),b=(0,m.wf)(b),c=window.document.createElement("div");c.className="comments-post-container";a.appendChild(c);c.appendChild(b);b=new eD(b);b.reset();c=(0,m.F)(a,"id");b.cb.reply_parent_id.value=c;if(a=(0,m.F)(a,"tag"))b.k=a;b.focus()}};
var yD=function(a,b){if(uD(!1)&&!(0,m.F)(a,"voted")){var c=(0,m.F)(a,"id"),d=(0,m.t)("VIDEO_ID"),e=(0,m.F)(a,"score")||"0",g=b?1:-1;(0,m.uc)(a,"voted",g+"");b?(0,m.jd)(a,"voted-down","voted-up"):(0,m.jd)(a,"voted-up","voted-down");c={a:g,id:c,video_id:d,old_vote:e};(d=(0,m.F)(a,"tag"))&&(c.tag=d);(0,m.V)("/comment_voting",{format:"XML",method:"POST",ha:c,ga:{session_token:(0,m.Lc)("comment_voting")}})}};
var zD=function(a){var b=(0,m.F)(a,"id"),c=(0,m.t)("VIDEO_ID");(0,m.I)(a,"has-child");(0,m.H)(a,"child");var d=(0,m.J)("parent-comment-loading");if(d){var e=(0,m.wf)(d);(0,m.be)(e,a);m.T.show(e)}(0,m.V)("/comment_servlet?get_comment_parent=1",{format:"XML",method:"POST",ga:{comment_id:b,entity_id:c,session_token:(0,m.Lc)("comment_servlet")},onSuccess:function(b,c){var d=window.document.createElement("ul");d.innerHTML=c.html_content;d=(0,m.he)(d);(0,m.be)(d,a);(0,m.M)(e);(0,m.nq)(d)},onError:function(b,
c){(0,m.H)(a,"has-child");(0,m.I)(a,"child");(0,m.M)(e);c&&c.error_message?window.alert(c.error_message):window.alert("Request failed, please try later.")}})};
var AD=function(a,b,c){var d=new m.uv((0,m.t)("WATCH_CONTEXT_CONTAINER_TEMPLATE")),e=new m.uv((0,m.t)("WATCH_CONTEXT_VIDEO_TEMPLATE")),g=new m.uv((0,m.t)("WATCH_CONTEXT_PLAYLIST_TEMPLATE")),h=new m.uv((0,m.t)("WATCH_CONTEXT_APPBAR_TEMPLATE")),k=a.clickindex,p=a.type,v=[];(0,m.z)(a.items,function(a,b){var c,d=b==k;switch(a.type){case "playlist":c=BD(a,g,d,p);break;case "video":c=CD(a,e,d,p)}c&&v.push(c)});if(v.length){var y=v.length,v=v.join(""),d=DD(a,d,v);c&&(c.innerHTML=ED(a,h,y));b.innerHTML=d;
(0,m.uc)(b,"context-type",p);if(a=(0,m.J)("context-image"))b=(0,m.F)(a,"context-image"),a.src=b}};
var DD=function(a,b,c){var d={};(0,m.Ja)(FD,function(b,c){d[b]=a[c]});d.container_classes="context-"+a.type+(a.image?" context-has-image":"");var e="";m.sA.test(a.source)?e="rtl":m.rA.test(a.source)&&(e="ltr");d.title_dir=e;d.item_list="__item_list__";d.feature="g-context-"+a.type;a.subsource?(d.headline=a.source,d.more_from=a.subsource):(d.headline="search"==a.type?(0,m.G)("WATCH_CONTEXT_MORE_RESULTS"):(0,m.G)("WATCH_CONTEXT_MORE_FROM"),d.more_from=a.source);return b.Pa(d).replace("__item_list__",
c)};var ED=function(a,b,c){var d={};(0,m.Ja)(FD,function(b,c){d[b]=a[c]});d.item_count=c;c="";m.sA.test(a.source)?c="rtl":m.rA.test(a.source)&&(c="ltr");d.title_dir=c;a.subsource?(d.headline=a.source,d.more_from=a.subsource):(d.headline="search"==a.type?(0,m.G)("WATCH_CONTEXT_MORE_RESULTS"):(0,m.G)("WATCH_CONTEXT_MORE_FROM"),d.more_from=a.source);return b.Pa(d)};
var BD=function(a,b,c,d){var e={};(0,m.Ja)(GD,function(b,c){e[b]=a[c]});e.playlist_video_id=a.videos[0];"channel"==d&&(e.action_username="");e.item_classes="";e.item_classes=a.actionverb?e.item_classes+" show-action":e.item_classes+" show-username";c&&(e.item_classes+=" context-playing");e.feature="g-context-"+d;return b.Pa(e)};
var CD=function(a,b,c,d){var e={};(0,m.Ja)(HD,function(b,c){e[b]=a[c]});"channel"==d&&(e.action_username="");e.item_classes="";e.item_classes=a.actionverb?e.item_classes+" show-action":"channel"==d?e.item_classes+" show-viewcount":e.item_classes+" show-username";c&&(e.item_classes+=" context-playing");e.feature="g-context-"+d;return b.Pa(e)};
var ID=function(){var a=(0,m.J)("watch-context-container");if(a){var b=(0,m.J)("appbar-context-items"),c;c=(c=(0,m.t)("VIDEO_ID"))?(0,m.ej)("context-"+c,IB):null;var d;c?(window.ytspf||{}).enabled&&c.propagated&&0<a.children.length?(c.open&&(0,m.uc)(a,"start-open","true"),JD(c.clickindex),d=!1):d=!0:d=!1;d&&(AD(c,a,b),KD(a,c.open,b))}};
var KD=function(a,b,c){m.T.show(a);c&&m.T.show(c);(0,m.u)(function(){(0,m.H)(a,"context-visible");c&&(0,m.H)(c,"context-visible")},0);LD();b&&(0,m.uc)(a,"start-open","true");if((0,m.t)("WATCH_CONTEXT_GEN204")){var d=(0,m.F)(a,"context-type"),d=d?"context-type="+d:"";b?(0,m.hf)("context-rendered-open",d,void 0):(0,m.hf)("context-rendered-closed",d,void 0)}};
var JD=function(a){var b=(0,m.K)("guide-context-item",(0,m.J)("watch-context-item-list"));(0,m.z)(b,function(b,d){d==a?(0,m.H)(b,"context-playing"):(0,m.I)(b,"context-playing")})};var LD=function(){var a=(0,m.J)("watch-context-item-list"),a=$A(m.Cn.getInstance(),a);(0,m.z)(a,function(a){(0,m.rq)(a)})};var MD=function(){var a=(0,m.l)("yt.www.guide.isLoaded"),b=(0,m.t)("WATCH_RELATED_DELAY"),a=!a||!a();ND(a,b)};
var ND=function(a,b){var c=3E3==b;if(a){var d=["guide"];c&&d.push("related");OD(d,function(){(0,m.w)(PD.guide)});PD.guide=(0,m.u)(function(){(0,m.S)(QD);RD(d)},3E3)}!b||a&&c||(PD.related=(0,m.u)(function(){RD(["related"])},b));c=["comments"];(0,m.t)("DELAY_LOAD_FOOTER")&&c.push("footer");SD(c)};var OD=function(a,b){QD=(0,m.Pf)((0,m.J)("guide-loading-toggle"),"click",function(c){b&&!1===b(c)||TD(a,!0)})};
var SD=function(a){var b=(0,m.J)((0,m.t)("IS_ACTIVE_LIVE_VIDEO")?"watch7-sidebar-discussion":"watch-discussion");if((0,m.pc)(b)&&1==b.nodeType){(0,m.Q)(b,"scrolldetect");(0,m.uc)(b,"scrolldetect-callback","comments-delay-load");var c=(0,m.C)()+1E3;(0,m.vt)({"comments-delay-load":function(){(0,m.u)(function(){TD(a)},c-(0,m.C)())}})}};var TD=function(a,b){a=UD(a);a.length&&((0,m.ac)(a,"guide")&&(0,m.B)((0,m.l)("yt.www.guide.MANUAL_LOADING")),RD(a,b),VD=(0,m.Qc)(VD,a))};
var UD=function(a){return(0,m.Cb)(a,function(a){return!(0,m.ac)(VD,a)})};
var RD=function(a,b){var c=(0,m.t)("VIDEO_ID");if(!c&&((0,m.ja)(a,"comments"),!a||!a.length))return;var d={frags:a.join(","),v:c};(0,m.ac)(a,"comments")&&(0,m.t)("IS_DISTILLER")&&(d.distiller="1");var e=(0,m.$e)(window.location.href);e&&(0,m.z)(WD,function(a){a in e&&(d[a]=e[a])});var c=(0,m.Te)("/watch_fragments_ajax",d),g=(0,m.bf)({session_token:(0,m.Lc)("watch_fragments_ajax")});XD.push(window.spf.load(c,{method:"POST",postData:g,onSuccess:function(){if((0,m.ac)(a,"comments")){if(!(0,m.yy)()){var c=
(0,m.J)("comments-view");YD=new mD((0,m.J)("watch-discussion"));ZD.push((0,m.Sf)(c,"click",rD,"comment-action"));if(c=(0,m.J)("comments-textarea"))c.disabled=!1,c.id="";(0,m.t)("COMMENT_OPEN_REPLY_BOX")&&(c=(0,m.K)("comment",(0,m.J)("linked-comments-header")),xD(c[c.length-1]));(0,m.nq)((0,m.J)("comments-view"))}(c=(0,m.t)("JS_COMMENTS_MODULES"))&&(0,m.Ma)(c)}if((0,m.ac)(a,"guide")){(c=(0,m.l)("yt.www.guide.setup"))&&c(b);var c=(0,m.t)("GUIDE_SELECTED_ITEM"),d=(0,m.l)("yt.www.guide.selectGuideItem");
d&&d(c);(0,m.B)("appbar-guide-delay-load")}(0,m.B)("yt-www-pageFrameCssNotifications-load");(0,m.ac)(a,"related")&&((0,m.nq)((0,m.J)("watch-related")),c=(0,m.t)("RELATED_PLAYER_ARGS"),d=(0,m.t)("PLAYER_REFERENCE"),c&&d&&d.updateVideoData&&d.updateVideoData(c),(0,m.t)("SKIP_RELATED_ADS")||gC())}}))};
var $D=function(){(0,m.z)(XD,function(a){a&&a.abort()});XD.length=0;for(var a in PD)(0,m.w)(PD[a]);PD={};(0,m.S)(QD);qD&&(qD.destroy(),qD=null);YD&&(YD.destroy(),YD=null);(0,m.zy)();(0,m.S)(ZD);ZD.length=0;VD=[]};var aE=function(){(0,m.Sc)((0,m.mv)())&&(0,m.Sc)((0,m.ov)())||bE();if((0,m.pv)()){var a=cE;"html5"!=a.getPlayerType()&&a.writePlayer("html5")}};
var dE=function(a){var b=(0,m.qv)();if((0,m.Yu)(b,a)&&(b=cE,"html5"!=b.getPlayerType())){var c=b.getVideoData().video_id,d=b.getCurrentTime(),d=(0,m.Bx)(d),e={key:a,videoId:c,currentTime:d},g="Setting the delayed connect data: "+(0,m.Li)(e);(0,m.Pw)(m.Sw,"RC",g);!(0,m.sx)(m.gx.getInstance(),a)&&(a=(0,m.tx)(m.gx.getInstance(),a))&&(g=(0,m.Xu)(),e.pairingCode=g,(0,m.fx)(a.id,g,c,d));(0,m.bj)("yt-remote-delayed-connect-key",e);b.writePlayer("html5")}};
var bE=function(){var a=cE;a.updateRemoteReceivers&&a.updateRemoteReceivers((0,m.qv)())};
var eE=function(){if(!fE){var a=(0,m.l)("ytplayer.config");if(a&&(a=(0,m.vb)(a),fE=(0,m.Nx)("player-api",a),(0,m.qa)("PLAYER_REFERENCE",fE),fE)){var b=fE;b.addEventListener("onReady",gE);b.addEventListener("onStateChange",hE);b.addEventListener("RATE_SENTIMENT",iE);b.addEventListener("SHARE_CLICKED",jE);b.addEventListener("SIZE_CLICKED",kE);b.addEventListener("onError",lE);b.addEventListener("WATCH_LATER",mE);b.addEventListener("onAdStart",nE);b.addEventListener("SUBSCRIBE",oE);b.addEventListener("UNSUBSCRIBE",
pE);b=fE;(0,m.Vw)();cE=b;cE.addEventListener("onReady",aE);cE.addEventListener("onRemoteReceiverSelected",dE);b=m.gx.getInstance();b.U("onlineReceiverChange",bE);qE=(0,m.x)("yt-remote-cast-device-tab-projected",dE);a.args.has_mdx_screens&&(0,m.jx)(b);rE();sE=(0,m.Kc)(rE,1E3);tE.push((0,m.x)("player-shortcut-rewind",uE));tE.push((0,m.x)("player-shortcut-fast-forward",vE));tE.push((0,m.x)("player-shortcut-play-pause",wE));tE.push((0,m.x)("watch-list-change",xE));yE.push((0,m.x)("sentiment-like",(0,m.D)(m.Mk,
"like")),(0,m.x)("sentiment-dislike",(0,m.D)(m.Mk,"dislike")),(0,m.x)("sentiment-indifferent",(0,m.D)(m.Mk,"indifferent")))}}};var xE=function(){var a=fE;a&&zE&&a.updatePlaylist()};var AE=function(a,b){var c=BE();if(c){var d=(0,m.$g)(c,"").split(","),d=(0,m.Cb)(d,function(b){return 0!=b.indexOf(a)&&!!b.length});4<=d.length&&d.shift();d.push(a+":"+b);(0,m.Yg)(c,d.join(","),1814400)}};
var CE=function(a){var b=BE();if(b){var c=(0,m.$g)(b,"").split(","),c=(0,m.Cb)(c,function(b){return 0!=b.indexOf(a)});0==c.length?(0,m.ah)(b):(0,m.Yg)(b,c.join(","),1814400)}};var DE=function(a){var b=(0,m.Qq)();if(b){a&&(0,m.qa)("RESUME_COOKIE_NAME",a);a=(0,m.t)("VIDEO_ID");var c=b.getDuration(),b=Math.floor(b.getCurrentTime());0==c||120>=b||b+120>=c?CE(a):AE(a,Math.floor(b))}};
var EE=function(){DE();if((0,m.t)("IS_RESUMABLE_PLAYBACK")){var a=fE;if(a){var b=(0,m.t)("VIDEO_ID"),c=a.getDuration(),a=Math.floor(a.getCurrentTime());0==c||20>=a||(0,m.Na)("/save_resume_204?"+(0,m.bf)({v:b,t:a.toString()}))}}};var gE=function(){zE=!0;BE()&&(0,m.R)(window,"beforeunload",EE)};var hE=function(a){(0,m.B)("player-state-change",a)};var oE=function(a){(0,m.B)("player-subscribe",a)};var pE=function(a){(0,m.B)("player-unsubscribe",a)};var lE=function(a){(0,m.B)("player-error",a)};
var kE=function(a){(0,m.Yg)("wide",a?"1":"0");(0,m.B)("player-resize",a)};var iE=function(a){(0,m.B)("player-sentiment",a)};var jE=function(){(0,m.B)("player-share")};var mE=function(a){(0,m.B)("player-watchlater",a)};var nE=function(a){(0,m.B)("player-ad-start",a)};var wE=function(){var a=fE;a&&(2==a.getPlayerState()?a.playVideo():a.pauseVideo())};var vE=function(){var a=fE;if(a){var b=a.getCurrentTime();a.seekTo(b+10)}};var uE=function(){var a=fE;if(a){var b=a.getCurrentTime();a.seekTo(b-10)}};
var FE=function(a,b){var c=fE;if(c){var d=null!=b?b:!0;c.seekTo(a,!0);d&&window.scroll(0,0);c.playVideo()}};var rE=function(){if(zE){var a=window.location.hash;a!=GE&&(GE=a,a=(0,m.af)(a),"t"in a&&a.t!=HE.t&&FE((0,m.Iv)(a.t),!1),HE=a)}};var BE=function(){return(0,m.t)("RESUME_COOKIE_NAME")};
var IE=function(a,b,c){this.b=a;this.D=b;this.Y=this.P=this.V=this.J=this.R=this.Z=this.ba=this.k=this.H=this.Sq=this.Tq=this.M=this.F=this.j=this.K=this.eh=this.G=null;(0,m.V)("/playlist_ajax",{ha:{action_get_addto_panel:1,video_id:this.D},onSuccess:function(a,b){JE(this,b.html);c()},W:this})};
var JE=function(a,b){a.b.innerHTML=b;a.K=(0,m.L)("sort-playlists",a.b);a.j=(0,m.L)("playlist-items",a.b);a.F=(0,m.L)("added-to-message",a.b);a.M=(0,m.L)("added-to-message-title",a.b);a.Tq=(0,m.L)("note-added-message",a.b);a.Sq=(0,m.L)("note-added-message-title",a.b);a.H=(0,m.L)("create-playlist",a.b);a.H&&(a.k=(0,m.L)("new-playlist-title",a.b),a.ba=(0,m.L)("create-new-playlist",a.b));a.Z=(0,m.R)(a.K,"change",(0,m.q)(a.kA,a));a.R=(0,m.R)(a.H,"submit",(0,m.q)(a.oA,a));a.J=(0,m.Sf)(a.b,"click",(0,m.q)(a.mA,
a),"playlist-item");a.V=(0,m.Sf)(a.b,"click",(0,m.q)(a.nA,a),"save-note");a.P=(0,m.Sf)(a.b,"click",(0,m.q)(a.lA,a),"cancel-note");a.Y=(0,m.R)(a.k,"keyup",(0,m.q)(a.pA,a));KE(a,a.K.value);(0,m.Sl)()};var LE=function(a){(0,m.S)(a.Z);(0,m.S)(a.R);(0,m.S)(a.J);(0,m.S)(a.V);(0,m.S)(a.P);(0,m.S)(a.Y)};
var KE=function(a,b){var c={updated:(0,m.D)(a.Cv,"time-updated"),created:(0,m.D)(a.Cv,"time-created"),privacy:a.aH,"a-z":a.Dv,"z-a":a.bH}[b];if(c){var d=(0,m.Pc)((0,m.K)("playlist-item",a.j));ME(a,d.sort((0,m.q)(c,a)))}};var ME=function(a,b){var c=window.document.createDocumentFragment();(0,m.z)(b,function(a){c.appendChild(a)});(0,m.ae)(a.j);(0,m.$d)(a.j,c)};
var NE=function(a,b){(0,m.Q)(b,"loading");(0,m.Lj)(b,{W:a,onSuccess:function(a,d){(0,m.pf)(b,"loading");d.html?(LE(this),JE(this,d.html),d.show_feed_privacy_dialog&&(0,m.B)("SHOW-FEED-PRIVACY-ADD-TO-PLAYLIST-DIALOG",d.video_id,d.playlist_id)):d.errors&&this.Nj(d.errors[0])}})};
var OE=function(a,b){(0,m.Q)(b,"loading");(0,m.Lj)(b,{format:"XML",ga:{session_token:(0,m.Lc)("addto_ajax"),setvideo_id:a.G},W:a,onSuccess:function(){PE(this);(0,m.pf)(b,"loading");var a=(0,m.L)("playlist-name",b);this.Sq.innerHTML=a.value;a=this.Tq;this.eh&&m.T.hide(this.eh);this.eh=a;m.T.show(a)},onError:function(a,d){(0,m.pf)(b,"loading");this.Nj(d.errors[0])}})};var PE=function(a){var b=(0,m.L)("selected",a.b);b&&((0,m.pf)(b,"selected"),a.G=null)};
var QE=function(){(0,m.r)("yt.net.apiloader.onApiLoaded_GOOGLE_JSAPI",function(){RE()})};var RE=function(){SE.GOOGLE_JSAPI=!0;(0,m.z)(TE.GOOGLE_JSAPI,function(a){a.call()});delete TE.GOOGLE_JSAPI};
var UE=function(a){this.j=a;this.F=this.eo=!1;this.D=this.k=this.b=null;var b=(0,m.q)(this.H,this),c=(0,m.t)("HL_LOCALE")||"en";if(a=VE.GOOGLE_JSAPI)SE.GOOGLE_JSAPI?b.call():(TE.GOOGLE_JSAPI||(TE.GOOGLE_JSAPI=[]),TE.GOOGLE_JSAPI.push(b),WE.GOOGLE_JSAPI||(QE(),b={callback:"yt.net.apiloader.onApiLoaded_GOOGLE_JSAPI"},c&&(b.language=c),a=(0,m.Te)(a,b),c=window.document.createElement("script"),c.src=a,window.document.body.appendChild(c),WE.GOOGLE_JSAPI=!0))};
var XE=function(a){var b=(0,m.J)("stats-optout-form");b&&(m.T.hide("stats-optout-success"),m.T.hide("stats-optout-error"),(0,m.Lj)(b,{format:"XML",ha:{opt_out:a},onSuccess:function(){this.eo=a;m.T.show("stats-optout-success")},onError:function(){(0,m.J)("stats-opt-out-chbox").checked=!this.eo;m.T.show("stats-optout-error")}}))};var YE=function(a,b){var c=(0,m.F)(a,b);if(c){var d=(0,m.P)(a,"watch-actions-stats-rats"),e=(0,m.F)(d,"current-"+b);e!=c&&((0,m.jd)(d,e,c),(0,m.uc)(d,"current-"+b,c))}};
var ZE=function(a,b,c){a=(0,m.L)("watch-actions-stats-rats",a.j);if(!a)return null;b=(0,m.F)(a,"current-"+b);return c&&b&&0==b.lastIndexOf(c,0)?b.substr(c.length):b};var $E=function(a){if(a.b&&a.F&&a.k){var b=ZE(a,"metric-css","stats-metric-"),c=ZE(a,"mode-css","stats-mode-");b&&c&&(a.D||(a.D=new window.google.visualization.LineChart(a.k)),aF(a,a.D,a.k,a.b.day||{},b in a.b?a.b[b][c]||{}:{}))}};
var aF=function(a,b,c,d,e){var g=new window.google.visualization.DataTable;g.addColumn("date","Date");g.addColumn("number","value");"cmp_data"in e?(g.addColumn("number","cmp_data"),d=WB(d.data||[],e.data||[],e.cmp_data||[])):d=WB(d.data||[],e.data||[]);(0,m.z)(d,function(a){a[0]=bF(a[0]);g.addRow(a)});e=e.opt||{};"hAxis"in e&&"viewWindow"in e.hAxis&&(d=e.hAxis.viewWindow,"min"in d&&!(d.min instanceof Date)&&(d.min=bF(d.min)),"max"in d&&!(d.max instanceof Date)&&(d.max=bF(d.max)));d=(0,m.ne)(c);(0,m.M)(c);
c.style.left="-5000px";(0,m.$d)(a.j,c);try{b.draw(g,e)}catch(h){throw h;}finally{c.style.left="",(0,m.M)(c),d&&(0,m.$d)(d,c)}};var bF=function(a){return new Date(a+6E4*(new Date(a)).getTimezoneOffset())};
var cF=function(a,b){this.F=a;this.J=b;this.j=(0,m.J)("watch-like-dislike-buttons");this.k="action-panel-details";var c=(0,m.F)(this.j,"vote-state"),c=(0,window.parseInt)(c,10);(0,window.isNaN)(c)&&(c=2);(0,m.tc)(this.j,"vote-state");this.D=c;this.K=null;this.b=[];this.qe=[];this.G=new m.oa;this.H=window.NaN;dF(this);eF(this,this.k);c=(0,m.af)(window.location.hash).action;"share"==c?this.pr():"flag"==c?fF(this,"action-panel-report"):"stats"==c&&fF(this,"action-panel-stats");(0,m.t)("RECIPROCAL_CIRCLE_ADD_PROMO")&&
gF(this)};var hF=function(a){switch(a){case "action-panel-share":(0,m.Uj)("share");(0,m.t)("CONVERSION_CONFIG_DICT")&&(0,m.Kk)("share",(0,m.t)("CONVERSION_CONFIG_DICT").uid||"");break;case "action-panel-addto":(0,m.Uj)("add_to_playlist")}};
var dF=function(a){a.qe.push((0,m.x)("player-share",a.pr,a));a.qe.push((0,m.x)("player-state-change",a.eF,a));a.qe.push((0,m.x)("player-sentiment",a.aF,a));a.qe.push((0,m.x)("livestreaming-likes-updated",a.dF,a));a.b.push((0,m.Sf)(a.F,"click",(0,m.q)(a.$E,a),"action-panel-trigger"));if((0,m.t)("LOGGED_IN")){var b=(0,m.J)("watch-dislike");a.b.push((0,m.R)((0,m.J)("watch-like"),"click",(0,m.q)(a.ZE,a)));a.b.push((0,m.R)(b,"click",(0,m.q)(a.YE,a)))}(b=(0,m.J)("watch-share-button"))&&a.b.push((0,m.R)(b,
"click",(0,m.q)(a.bF,a)));var c=(0,m.J)("donation-box");if(c){var d=(0,m.L)("google-checkout-price",c);a.b.push((0,m.R)(d,"change",function(){(0,m.L)("google-checkout-donate",c).disabled=1>d.selectedIndex}));if(b=(0,m.J)("watch-donation-button")){var e=new m.Yx;(0,m.Nv)(e,b);(0,m.E)(a.G,e)}}a.qe.push((0,m.x)("watch-video-liked",(0,m.q)(a.cF,a)))};
var iF=function(a,b){var c=(0,m.t)("VIDEO_ID");jF(!1);(0,m.Vj)(c,b,{xb:(0,m.t)("PLAYBACK_ID"),pv:(0,m.t)("STATION_ID"),onSuccess:(0,m.q)(function(a,e){var g;t:switch(b){case 1:g="sentiment-dislike";break t;case 0:g="sentiment-like";break t;default:g="sentiment-indifferent"}(0,m.B)(g,c);0==b?((0,m.B)("watch-video-liked"),(0,m.jd)(this.j,"disliked","liked")):1==b?((0,m.B)("watch-video-disliked"),(0,m.jd)(this.j,"liked","disliked")):(0,m.I)(this.j,"liked","disliked");g=(0,m.J)("watch-like");var h;if(h=
0==b?(0,m.F)(g,"unlike-tooltip"):(0,m.F)(g,"like-tooltip"))(0,m.tc)(g,"tooltip-text"),g.title=h;this.D=b;0==b&&"True"==e.show_feed_privacy_dialog&&(0,m.B)("SHOW-FEED-PRIVACY-LIKE-DIALOG",c)},a),onError:(0,m.q)(function(){kF(this,"action-panel-error")},a),Ba:(0,m.q)(function(){jF(!0)},a)})};var jF=function(a){var b=(0,m.J)("watch-like-dislike-buttons");(0,m.u)(function(){(0,m.yf)(b,a)},0)};var lF=function(a,b){fF(a,"action-panel-share",!1,b)};
var fF=function(a,b,c,d){var e=(0,m.J)("watch7-secondary-actions");aB(m.el.getInstance(),e);e=mF(a,(0,m.J)(b));(0,m.H)(e,"yt-uix-button-toggled");eF(a,b,d);c&&hF(b)};var nF=function(a){return(0,m.t)("ALLOW_RATINGS")?(0,m.t)("LOGGED_IN")?(0,m.t)("YPC_CAN_RATE_VIDEO")?!0:(kF(a,"action-panel-rental-required"),!1):(kF(a,"action-panel-login"),!1):(kF(a,"action-panel-ratings-disabled"),!1)};
var eF=function(a,b,c){if("action-panel-none"!=b){var d=(0,m.J)(b),e=!!(0,m.F)(d,"auth-required"),d=!!(0,m.F)(d,"panel-loaded");if(e&&!(0,m.t)("LOGGED_IN"))kF(a,"action-panel-login");else if(d)kF(a,b);else switch(b){case "action-panel-details":b=(0,m.J)("action-panel-details");oF(a);(0,m.uc)(b,"panel-loaded","true");kF(a,"action-panel-details");break;case "action-panel-share":pF(a,c);break;case "action-panel-addto":b=(0,m.J)("action-panel-addto");new IE(b,(0,m.t)("VIDEO_ID"),m.ed);(0,m.uc)(b,"panel-loaded",
"true");kF(a,"action-panel-addto");break;case "action-panel-transcript":qF(a);break;case "action-panel-stats":rF(a);break;case "action-panel-report":sF(a)}}};
var oF=function(a){var b=(0,m.L)("yt-uix-expander",(0,m.J)("action-panel-details"));b&&(a.b.push((0,m.R)((0,m.J)("watch-description-content"),"click",function(){if((0,m.kd)(b,"yt-uix-expander-collapsed")){var a=m.Ml.getInstance(),d=a.b(b);d&&((0,m.I)(d,(0,m.W)(a,"collapsed")),a.D(d,"expander-action"))}})),(0,m.kd)(b,"yt-uix-expander-collapsed")&&a.b.push((0,m.Pf)(b,"click",function(){var a=(0,m.J)("watch-source-videos-list");a&&NB(a)})))};
var pF=function(a,b){var c=RB(),d=QB(),e=(0,m.J)("action-panel-share"),g=new m.oz((0,m.J)("watch-actions-share-panel"),c,d,function(){m.T.hide("watch-actions-share-loading")},!0,null,b),h=(0,m.Kc)(function(){var a=(0,m.Qq)(),b=m.T.Va(e);if(a&&b){var a=a.getCurrentTime(),b=Math.floor(a/3600),c=Math.floor(a%3600%60),a=(0<b?b+":":"")+(0,m.Yc)(Math.floor(a%3600/60),0<b?2:1)+":"+(0,m.Yc)(c,2);g.Bj(a)}else(0,m.Jc)(h)},1E3);a.H=h;(0,m.uc)(e,"panel-loaded","true");kF(a,"action-panel-share")};
var rF=function(a){var b=(0,m.J)("action-panel-stats");b&&(a.K=new UE(b),OB((0,m.q)(function(a,d,e){e?(b.innerHTML=a,this.K.load(d)):kF(this,"action-panel-error")},a)),(0,m.uc)(b,"panel-loaded","true"),kF(a,"action-panel-stats"))};
var sF=function(a){var b,c=!1,d=!1,e=(0,m.J)("action-panel-report"),g=(0,m.q)(function(){kF(this,"action-panel-error")},a);(0,m.xh)((0,m.t)("REPORTVIDEO_CSS"));(0,m.Ka)((0,m.t)("REPORTVIDEO_JS"),(0,m.q)(function(){c=!0;d&&c&&tF(e,b)},a));PB((0,m.q)(function(a,k){k?(d=!0,b=a,d&&c&&tF(e,b)):g()},a));(0,m.uc)(e,"panel-loaded","true");kF(a,"action-panel-report")};var tF=function(a,b){a.innerHTML=b;(0,m.l)("yt.www.report.reportvideo.init")(!0)};
var qF=function(a){var b=(0,m.J)("action-panel-transcript");(0,m.l)("yt.www.watch.transcript.open")(function(){m.T.hide("watch-actions-transcript-loading");m.T.show((0,m.J)("watch-actions-transcript"))});(0,m.uc)(b,"panel-loaded","true");kF(a,"action-panel-transcript")};
var kF=function(a,b){var c=uF[a.k],d=uF[b],e=(0,m.J)(a.k),g=(0,m.J)(b),h=a.J;if(d==c)(0,m.I)(h,"action-panel-transition"),(0,m.I)(e,"action-panel-center","action-panel-left","action-panel-right"),m.T.show(e);else{a.k=b;m.T.show(e);h.style.height=h.clientHeight+"px";(0,m.H)(h,"action-panel-transition");if(d>c)var k="action-panel-right",p="action-panel-left";else k="action-panel-left",p="action-panel-right";(0,m.H)(e,"action-panel-center");(0,m.H)(g,k);m.T.show(g);(0,m.u)(function(){(0,m.I)(e,"action-panel-center");
(0,m.H)(e,p);(0,m.I)(g,k);(0,m.H)(g,"action-panel-center");(0,m.u)(function(){m.T.hide(e);(0,m.I)(e,p);(0,m.I)(g,"action-panel-center");(0,m.I)(h,"action-panel-transition");h.style.height=""},(0,m.Zp)(g))},0)}};var mF=function(a,b){var c=(0,m.K)("action-panel-trigger",a.F);return(0,m.Mb)(c,function(a){a=(0,m.F)(a,"trigger-for");return b.id==a})};
var gF=function(a){var b=(0,m.L)("yt-uix-clickcard-target",(0,m.J)("watch7-user-header")),c=(0,m.L)("rcap-dismiss-button",window.document);(0,m.Ep)("plus:follow",(0,m.Fp)(function(){var a=(0,m.L)("add-to-circle"),b=(0,m.l)("gapi.follow.render");b&&a&&(b(a,{href:(0,m.F)(a,"gplus-profile-url"),height:24,source:"youtube:topfans-follow-back"}),a.style.zIndex=2147483647)}));a.b.push((0,m.R)(c,"click",function(){(0,m.V)("/engagement_wizard_ajax",{method:"POST",ha:{action_dismiss_reciprocal_circle_add_promo:"1"},
ga:{session_token:(0,m.Lc)("engagement_wizard_ajax"),video_id:(0,m.t)("VIDEO_ID")}})}));m.Dl.getInstance().show(b)};var vF=function(){this.b=[];this.j=0;this.k=window.document.title;(0,m.Qq)()&&this.hu(1);this.b.push((0,m.x)("page-resize",this.xD,this));this.b.push((0,m.x)("player-state-change",this.hu,this));this.b.push((0,m.x)("player-resize",this.yD,this));this.zl()};var wF=function(a){1==a&&(0,m.it)()};
var xF=function(a,b){if(!yF&&b.swfcfg){var c=b.swfcfg.args,d=fE;d&&d.preloadVideoByPlayerVars&&c&&d.preloadVideoByPlayerVars(c);yF=!0}};
var zF=function(){var a=(0,m.J)("watch7-action-buttons"),b=(0,m.J)("watch7-action-panels");AF=null;a&&b&&(AF=new cF(a,b));BF=new vF;CF.push((0,m.x)("guide-loaded",ID));(0,m.uq)();(0,m.R)(window.document,"keypress",HB);YB();SB();if((0,m.t)("BRANDED_BACKGROUND_IMAGE")||(0,m.t)("BRANDED_BACKGROUND_COLOR")){(0,m.H)((0,m.J)("guide-container"),"branded");var a=(0,m.J)("player"),b=(0,m.t)("BRANDED_BACKGROUND_IMAGE"),c=(0,m.t)("BRANDED_BACKGROUND_COLOR");b&&(a.style.background="transparent url("+b+") no-repeat center top",
(0,m.kd)(window.document.body,"site-left-aligned")&&(a.style.backgroundPosition="left top"));c&&(a.style.backgroundColor=c)}a=(0,m.J)("watch7-sidebar");DF.push((0,m.Sf)(a,"click",dB,"related-action"));(0,m.t)("RADIO_ENTRYPOINT_RESUMES_CURRENTLY_PLAYING_VIDEO")&&DF.push((0,m.Sf)(a,"click",cB,"resumable-list"));EF.push((0,m.x)("prefetch",xF));(a=(0,m.t)("PLAYER_REFERENCE"))&&a.getPlayerState&&1==a.getPlayerState()?(0,m.it)():EF.push((0,m.x)("player-state-change",wF));m.Hb&&(!window.document.documentMode||
8>window.document.documentMode)&&FF.push((0,m.Sf)(window.document.body,"click",GF,"video-thumb"));(0,m.Pu)(1)};var GF=function(a){(0,m.ye)(a.target,"BUTTON")||a.currentTarget.click()};var HF=function(a,b){b.subscriptionId&&window.location.reload(!0)};m.iz.prototype.Bj=(0,m.Nb)(11,function(){if(this.vx){var a=(0,m.Qq)(),b=Math.round(1E3*a.getCurrentTime()),b=[b,b+1E3],b=(0,m.jz)(this,b,!0);(0,m.mz)(this,b,1!=a.getPlayerState())}});
m.oz.prototype.Bj=(0,m.Nb)(10,function(a){!this.b||(0,m.kd)(this.b,"focused")||this.Z||(this.b.value=a,this.wi(),m.T.Va(this.D)&&this.Y&&this.Y.Bj())});var gB="",iB=null,fB=null,DF=[],AB=null,CB=null,UB=[],TB=[],yE=[],YD,qD,BF,AF;m.f=XB.prototype;m.f.Eg=!1;m.f.qj=!1;
m.f.start=function(a){var b={start:0};b.end=a.scrollHeight-a.clientHeight;b.duration=b.end/3;b.Oi="linear";this.j=new m.wu(a,b);this.Eg=!0;this.b.listen(a,"click",this.yE);this.b.listen(a,"mouseover",this.AE);this.b.listen(a,"mouseout",this.xE);this.b.listen(a,"scroll",this.zE)};m.f.zE=function(){this.qj||this.Eg||((0,m.su)(this.j),this.qj=!0)};m.f.yE=function(){(0,m.su)(this.j);this.Eg=!1;this.qj=!0};m.f.AE=function(){(0,m.su)(this.j);this.Eg=!1};
m.f.xE=function(){this.Eg||this.qj||(this.j.k(),this.Eg=!0)};m.f.dispose=function(){this.b.removeAll();this.qj=this.Eg=!1;this.j=null;this.k=!0};m.f.va=function(){return this.k};var ZB,aC,yC="",zC="",DC=!1,eC=!1,lC=null,HC=null,KC=!1,GC=!1,MC=!1,WC=null,bC=null,TC=null,YC=null,EC=0,mC=null,nC=null,oC=null,OC=[],PC=[],RC=null,SC=null,NC=!1;(0,m.r)("yt.www.watch.ads.setAdId",function(a){window.ad_debug=a});(0,m.r)("yt.www.watch.ads.setCompanion",pC);(0,m.r)("yt.www.watch.ads.showForcedMpu",function(a){var b=rC(a,250);a=sC(a);pC(b,a)});(0,m.r)("yt.www.watch.ads.createGutSlot",hC);(0,m.r)("yt.www.watch.ads.handleMoveGutCompanion",function(){var a=(0,m.J)("google_companion_ad_div"),b=(0,m.J)("yt-gut-content");b?b.innerHTML="":(b=window.document.createElement("div"),b.id="yt-gut-content");a&&(a.innerHTML="",a.appendChild(b));qC()});
(0,m.r)("yt.www.watch.ads.setGutSlotSizes",function(a,b){if(mC){var c=mC.getSizes();(0,m.Rc)(c);b&&c.push(nC);a&&c.push(oC)}});(0,m.r)("yt.www.watch.ads.handleSetCompanion",tC);(0,m.r)("yt.www.watch.ads.handleSetCompanionForInstream",uC);(0,m.r)("yt.www.watch.ads.handleSetCompanionForFreewheel",vC);(0,m.r)("yt.www.watch.ads.handleHideCompanion",pC);(0,m.r)("yt.www.watch.ads.handleHideCompanionForInstream",pC);(0,m.r)("yt.www.watch.ads.handleCloseMpuCompanion",pC);
(0,m.r)("yt.www.watch.ads.handleSetAfvCompanionVars",wC);(0,m.r)("yt.www.watch.ads.handleShowAfvCompanionAdDiv",BC);(0,m.r)("yt.www.watch.ads.handleHideAfvInstreamCompanionAdDiv",CC);(0,m.r)("yt.www.watch.ads.AD_LOAD_TOPIC","watchads-adLoad");(0,m.r)("yt.www.watch.ads.companionSetupComplete",xC);(0,m.r)("yt.www.watch.ads.pauseVideo",AC);(0,m.r)("yt.www.watch.ads.loadAfc",iC);
(0,m.r)("yt.www.watch.ads.isAfcAdVisible",function(){var a=(0,m.J)("google_companion_ad_div");return a?(a=(0,m.he)(a))&&"IFRAME"==a.tagName?-1!=a.src.indexOf("youtube.com/ad_frame"):!1:!1});(0,m.r)("yt.www.watch.ads.checkInit",jC);(0,m.r)("yt.www.ads.pyv.pyvWatchAfcWithPpvCallback",function(a){LB(a);0<a.length&&KB()});(0,m.r)("yt.www.ads.pyv.pyvWatchAfcCallback",LB);(0,m.r)("yt.www.ads.pyv.pyvHomeAfcCallback",m.Ix);(0,m.r)("yt.www.ads.pyv.showPpvOnWatch",qB);
(0,m.r)("yt.www.ads.pyv.loadPyvIframe",JB);(0,m.r)("setCompanion",tC);(0,m.r)("setInstreamCompanion",uC);(0,m.r)("setFreewheelCompanion",vC);(0,m.r)("closeInPageAdIframe",pC);(0,m.r)("hideInstreamCompanion",pC);(0,m.r)("closeMpuCompanion",pC);(0,m.r)("setAfvCompanionVars",wC);(0,m.r)("showAfvCompanionAdDiv",BC);(0,m.r)("hideAfvInstreamCompanionAdDiv",CC);
(0,m.r)("setVideoWallCompanionTrackingUrl",function(a,b){yC=a;zC=b;window.addEventListener("message",function(a){"companion-setup-complete"==a.data?xC():"pause-video"==a.data&&AC()},!1)});m.f=eD.prototype;m.f.destroy=function(){(0,m.S)(this.F);this.F=[];(0,m.z)(this.D,function(a){(0,m.Jc)(a)});this.D=[];(0,m.tc)(this.cb,"initialized")};m.f.reset=function(){hD(this);jD(this);(0,m.I)(this.cb,"has-focus");this.Bf.disabled=!1;this.Nc.value="";fD(this);this.Nc.blur();this.k=null;this.destroy();(0,m.B)("comment-form-reset")};m.f.focus=function(){this.Nc.focus()};m.f.Zr=function(){this.Nc.readOnly||fD(this)};m.f.PA=function(a){if(this.H)switch(a.keyCode){case 13:this.Yr(a);break;case 27:this.reset()}};
m.f.$r=function(){(0,m.kd)(this.cb,"has-focus")||m.T.hide(this.mg);(0,m.H)(this.cb,"has-focus");(0,m.B)("comments-focus",this.cb)};m.f.OA=function(){(0,m.B)("comments-blur",this.cb)};
m.f.Yr=function(a){a.preventDefault();if(!this.Bf.disabled){this.Bf.disabled=!0;this.Nc.readOnly=!0;a=(0,m.Ze)((0,m.Bj)(this.cb));a.screen=(0,m.bf)({h:window.screen.height,w:window.screen.width,d:window.screen.colorDepth});var b=a.comment,b={return_ajax:"true",len:b.length,wc:b.split(/\s+/).length};this.cb.reply_parent_id.value&&(b.reply=1);this.k&&(b.tag=this.k);var c=(0,m.t)("PLAYBACK_ID");c&&(a.plid=c);(0,m.V)(this.cb.action,{format:"XML",method:"POST",ha:b,ga:a,Ba:function(a,b){var c=b.str_code;
switch(c){case "OK":c=window.document.createElement("ul");c.innerHTML=b.html_content;c=(0,m.he)(c);if(this.cb.reply_parent_id.value){var h=(0,m.ye)(this.cb,null,"comments-post-container"),k=(0,m.ye)(h,null,"comment");(0,m.M)(h);(0,m.jd)(k,"replying","has-child");(0,m.H)(c,"child");(0,m.ld)(c,"last",!(0,m.je)(k));(0,m.ce)(c,k)}else this.wz?this.Dr.appendChild(c):(0,m.de)(this.Dr,c,0),this.reset();(0,m.rq)(c);(0,m.B)("comment-submit-success");"True"==b.show_feed_privacy_dialog&&(0,m.B)("SHOW-FEED-PRIVACY-COMMENT-DIALOG",
(0,m.t)("VIDEO_ID"),b.time_created);break;case "PENDING":hD(this);this.Br.innerHTML=(0,m.G)("COMMENT_PENDING");(0,m.jd)(this.mg,"yt-alert-error","yt-alert-info");m.T.show(this.mg);break;default:lD(this,c,b)}this.Nc.readOnly=!1},W:this});(0,m.t)("CONVERSION_CONFIG_DICT")&&(0,m.Kk)("comment",(0,m.t)("CONVERSION_CONFIG_DICT").uid||"");(0,m.Uj)("comment")}};mD.prototype.destroy=function(){(0,m.S)(this.b);this.b=[]};mD.prototype.D=function(a){a.preventDefault();(0,m.kd)(a.currentTarget,"yt-uix-button-toggled")||(m.T.hide(this.Zs),(0,m.B)("comments-page-changing"),this.Mj?this.j(2):nD(this,(0,m.q)(this.j,this,2)))};
mD.prototype.j=function(a){var b=(0,m.J)("comments-view");b.appendChild(this.Mj);(0,m.rq)(b);if(b=(0,m.J)("comments-textarea"))b.disabled=!1,b.id="";if(b=(0,m.L)("comment-list",this.da)){var c=(0,m.L)("live-comments-setting",this.da);(0,m.B)("comments-page-changed",b,c,a)}else(0,m.B)("comments-page-changed");nD(this)};var ZD=[];var FD={clickindex:"click_index",link:"back_link",image:"image",source:"source",subsource:"subsource"},GD={actionuser:"action_username",actionuserthumb:"action_user_thumb",actionuserurl:"action_user_url",actionverb:"action_verb",count:"video_count",countlabel:"video_count_label",id:"playlist_id",listthumb:"list_thumb",title:"playlist_title",user:"user_name",videos:null},HD={actionuser:"action_username",actionuserthumb:"action_user_thumb",actionuserurl:"action_user_url",actionverb:"action_verb",id:"video_id",
time:"video_time",title:"video_title",user:"user_name",videothumb:"video_thumb",views:"view_count"};var QD,XD=[],PD={},WD="lc lch lcor lcai generate_fake_live_comments debugjs".split(" "),VD=[];var cE=null,qE=window.NaN;var fE,tE=[],zE=!1,GE="",HE={},sE=0;m.f=IE.prototype;m.f.dispose=function(){LE(this)};m.f.kA=function(a){a=a.currentTarget.value;KE(this,a);(0,m.V)("/playlist_ajax?action_update_addto_sort_criteria=1",{ha:{criteria:a}})};m.f.aH=function(a,b){var c=(0,m.F)(a,"is-private")||"",d=(0,m.F)(b,"is-private")||"";return(0,m.kc)(c,d)};m.f.Cv=function(a,b,c){b=(0,window.parseInt)((0,m.F)(b,a),10)||window.Infinity;return((0,window.parseInt)((0,m.F)(c,a),10)||window.Infinity)-b};
m.f.Dv=function(a,b){var c=(0,m.F)(a,"title")||"",d=(0,m.F)(b,"title")||"";return(0,m.kc)(c,d)};m.f.bH=function(a,b){return this.Dv(b,a)};m.f.oA=function(a){a.preventDefault();a=(0,m.L)("create-playlist",this.b);(0,m.mc)(this.k.value)||NE(this,a)};m.f.Nj=function(a){var b=(0,m.L)("added-to-error-message",this.b);(0,m.L)("yt-alert-content",b).innerHTML=a;m.T.show(b)};
m.f.mA=function(a){var b=a.currentTarget;(0,m.rf)(b,"selected")||(a.stopPropagation(),PE(this),(0,m.Q)(b,"loading"),a=(0,m.L)("added-to-error-message",this.b),m.T.hide(a,this.F),a=(0,m.F)(b,"full-list-id"),(0,m.Sr)({Kb:this.D,gl:a,JE:(0,m.J)("playlist-addto-top-checkbox").checked?"True":"False",onSuccess:(0,m.D)(this.SE,b),onError:(0,m.D)(this.RE,b),W:this}))};
m.f.SE=function(a,b,c){this.G=c.setvideo_id;(0,m.sf)(a,"loading","contains-selected-videos");this.M.innerHTML=(0,m.F)(a,"title");b=this.F;this.eh&&m.T.hide(this.eh);this.eh=b;m.T.show(b);(0,m.B)("PLAYLIST_UPDATED");b=(0,m.L)("playlist-video-count",a);b.innerHTML=(0,window.parseInt)(b.innerHTML,10)+1;"True"==c.show_private_video_warning&&(b=(0,m.L)("private-video-warning",(0,m.L)("watch-playlist-drawer")))&&m.T.show(b);b=(0,m.F)(a,"list-type");var d="favorites"==b;d||"watch-later"==b||(0,m.Q)(a,"selected");
d?(a="playlist-favorite",b="SHOW-FEED-PRIVACY-FAVORITE-DIALOG"):(a="playlist-addto",b="SHOW-FEED-PRIVACY-ADD-TO-PLAYLIST-DIALOG");(0,m.B)(a,this.D,c.full_list_id);"True"==c.show_feed_privacy_dialog&&(0,m.B)(b,this.D,c.full_list_id)};m.f.RE=function(a,b,c){(0,m.pf)(a,"loading");this.Nj(c.error_message)};m.f.nA=function(a){a.preventDefault();a=(0,m.P)(a.currentTarget,"playlist-note-form");OE(this,a)};m.f.lA=function(){PE(this)};m.f.pA=function(){this.ba.disabled=(0,m.mc)(this.k.value)};var VE={GOOGLE_MAPS_API:"//maps.google.com/maps/api/js?sensor=false",GOOGLE_LANGUAGE_API_VIRTUAL_KEYBOARD:"//www.google.com/jsapi?key=youtube-internal-vk",GOOGLE_LANGUAGE_API_INPUT_TOOLS:"//www.google.com/jsapi?key=youtube-internal-it",GOOGLE_PLUS_ONE:"//apis.google.com/js/platform.js",GOOGLE_JSAPI:"//www.google.com/jsapi"},WE={},SE={},TE={};UE.prototype.load=function(a){var b=(0,m.J)("stats-opt-out-chbox");b&&(this.eo=!b.checked,(0,m.R)(b,"change",(0,m.q)(function(){XE(!b.checked)},this)));(0,m.Sf)(this.j,"click",(0,m.q)(function(a){YE(a.currentTarget,"mode-css");$E(this)},this),"stats-mode-button");(0,m.Sf)(this.j,"click",(0,m.q)(function(a){YE(a.currentTarget,"top-site-css");YE(a.currentTarget,"metric-css");$E(this)},this),"stats-bragbar");(0,m.Yk)(m.jo);a&&(this.b=(0,m.Ki)(a));this.k=(0,m.L)("stats-chart-gviz",this.j);$E(this)};
UE.prototype.H=function(){window.google.load("visualization","1.0",{packages:["corechart"],callback:(0,m.q)(this.G,this),language:(0,m.t)("HL_LOCALE")||"en"})};UE.prototype.G=function(){this.F=!0;$E(this)};var uF={"action-panel-details":1,"action-panel-share":2,"action-panel-addto":3,"action-panel-transcript":4,"action-panel-stats":5,"action-panel-report":6,"action-panel-login":7,"action-panel-ratings-disabled":8,"action-panel-rental-required":9,"action-panel-error":10};m.f=cF.prototype;m.f.destroy=function(){(0,m.S)(this.b);this.b=[];(0,m.Da)(this.qe);this.qe=[];(0,m.Jc)(this.H);this.G.dispose()};m.f.ZE=function(){var a=0==this.D?2:0;nF(this)&&iF(this,a)};
m.f.YE=function(){var a=1==this.D?2:1;nF(this)&&iF(this,a)};m.f.cF=function(){fF(this,"action-panel-share",!0)};m.f.pr=function(){lF(this);hF("action-panel-share")};m.f.eF=function(a){0==a?(0,m.t)("SHARE_ON_VIDEO_END")&&lF(this,!0):((0,m.t)("SHARE_ON_VIDEO_PAUSE")&&2==a&&20<(0,m.Qq)().getCurrentTime()&&lF(this,!0),1==a&&(0,m.t)("SHARE_ON_VIDEO_START")&&lF(this,!0))};m.f.bF=function(){var a=(0,m.J)("watch7-secondary-actions");aB(m.el.getInstance(),a)};m.f.aF=function(a){nF(this)&&iF(this,a)};
m.f.$E=function(a){a=(0,m.F)(a.currentTarget,"trigger-for");var b=(0,m.J)("watch-share-button");b&&(0,m.kd)(b,"yt-uix-button-toggled")&&(0,m.I)(b,"yt-uix-button-toggled");eF(this,a);hF(a)};m.f.dF=function(a,b,c,d){var e=(0,m.J)("watch7-views-info"),g=(0,m.L)("likes-count",e);g&&(0,m.qe)(g,a);(a=(0,m.L)("dislikes-count",e))&&(0,m.qe)(a,b);if(b=(0,m.L)("video-extras-sparkbar-likes",e))b.style.width=c+"%";if(c=(0,m.L)("video-extras-sparkbar-dislikes",e))c.style.width=d+"%"};m.f=vF.prototype;m.f.destroy=function(){(0,m.w)(this.j);(0,m.Da)(this.b);this.b.length=0};m.f.xD=function(){this.zl()};m.f.hu=function(a){window.document.title=1==a?"\u25b6 "+this.k:this.k};
m.f.yD=function(a){a=!!a;var b=(0,m.J)("watch7-container"),c=(0,m.J)("player"),d=(0,m.J)("watch7-sidebar"),e=(0,m.Zp)(d);if(a)(0,m.H)(b,"watch-wide"),(0,m.H)(c,"watch-playlist-collapsed"),(0,m.w)(this.j),this.j=(0,m.u)((0,m.q)(this.zl,this),e);else if((0,m.I)(b,"watch-wide"),(0,m.I)(c,"watch-playlist-collapsed"),this.zl(),(0,m.rq)(d),a=(0,m.J)("watch7-playlist-tray-container"))a=(0,m.Zp)(a),(0,m.u)(pB,a)};
m.f.zl=function(){(0,m.w)(this.j);var a=(0,m.J)("player"),b=(0,m.kd)((0,m.J)("watch7-container"),"watch-wide"),c=(0,m.gn)();b?(b=1540<=c.width&&1040<=c.height,(0,m.t)("ENABLE_AUTO_LARGE")&&b?(0,m.jd)(a,"watch-medium","watch-large"):(0,m.jd)(a,"watch-large","watch-medium")):(0,m.I)(a,"watch-medium","watch-large")};var yF,EF=[];var FF=[],CF=[];var IF=[];(0,m.r)("yt.www.watch.player.init",eE);
(0,m.r)("yt.www.watch.player.dispose",function(){(0,m.Jc)(sE);(0,m.Tf)(window,"beforeunload",EE);(0,m.Da)(yE);yE=[];(0,m.Da)(qE);qE=window.NaN;m.gx.getInstance().ra("onlineReceiverChange",bE);cE&&(cE.removeEventListener("onRemoteReceiverSelected",dE),cE.removeEventListener("onReady",aE),cE=null);var a=(0,m.Tw)();if(a){(0,m.Rw)("API disposed");var b=m.Mw,c=(0,m.l)("yt.mdx.remote.debug.handlers_");(0,m.ja)(c,b);a.setReloadTabRequestHandler&&a.setReloadTabRequestHandler(m.ed);a.removeReceiverListener("YouTube",
m.Yw);(0,m.Zw)(null)}m.Ww=!1;fE&&(a=fE,a.removeEventListener("onReady",gE),a.removeEventListener("onStateChange",hE),a.removeEventListener("RATE_SENTIMENT",iE),a.removeEventListener("SHARE_CLICKED",jE),a.removeEventListener("SIZE_CLICKED",kE),a.removeEventListener("onError",lE),a.removeEventListener("WATCH_LATER",mE),a.removeEventListener("onAdStart",nE),a.removeEventListener("SUBSCRIBE",oE),a.removeEventListener("UNSUBSCRIBE",pE),fE.stopVideo&&fE.stopVideo());fE=null;zE=!1;GE="";HE={};(0,m.Da)(tE);
tE.length=0});(0,m.r)("yt.www.watch.player.seekTo",FE);(0,m.r)("yt.www.watch.player.play",function(){var a=fE;a&&a.playVideo()});(0,m.r)("yt.www.watch.player.pause",function(){var a=fE;a&&a.pauseVideo()});(0,m.r)("yt.www.watch.player.saveResumeOffset",DE);(0,m.r)("yt.www.watch.player.navigate",function(a){(0,m.mo)(a);return!0});
(0,m.r)("yt.www.watch.player.handleEndPreview",function(a){var b=fE;b&&b.stopVideo&&b.stopVideo();(b=(0,m.J)("watch-checkout-offers"))&&(0,m.B)("ypc-init-purchase-for-container",b,a)});(0,m.r)("yt.tracking.social.onAdvertiserVideoView",m.Jk);(0,m.r)("checkCurrentVideo",function(a,b,c){var d=(0,m.t)("VIDEO_ID");d&&d!=a&&(a=c?c:(0,m.cf)(window.location.href,{v:a,list:b}))&&(0,m.lo)(a)});
(0,m.r)("yt.www.watch.related.loadMore",function(){m.T.hide("watch-more-related-button");m.T.show("watch-more-related");MB(function(){(0,m.rq)((0,m.J)("watch-more-related"))})});(0,m.r)("yt.www.comments.initForm",pD);(0,m.r)("yt.www.thumbnaildelayload.classifyAndLoadVisibleImages",m.nq);(0,m.r)("yt.www.watch.lists.loadThumbnails",pB);
(0,m.r)("yt.www.watch.lists.getState",function(){var a=[],b={},c=-1,d=[],e=fB;if(!e)return null;(0,m.z)(e.getElementsByTagName("li"),function(e,g){(0,m.rf)(e,gB)&&(c=g);var p=(0,m.F)(e,"video-id"),v=(0,m.F)(e,"video-username"),y=(0,m.F)(e,"video-title"),v={id:p,username:v,title:y},y=(0,m.F)(e,"video-clip-start"),A=(0,m.F)(e,"video-clip-end");a[g]=p;b[p]=v;d[g]={start:y,end:A}});var e=m.Bq,e=(0,m.vl)(m.el.getInstance(),e),g=m.Dq;return{author:(0,m.F)(g,"list-author"),autoPlay:e,clipRanges:d,index:c,
listTitle:(0,m.F)(g,"list-title"),listDescription:(0,m.F)(g,"list-description"),videoData:b,videoIds:a}});(0,m.r)("yt.www.watch.context.loadThumbnails",LD);(0,m.r)("yt.www.watch.activity.getTimeSinceActive",m.zq);(0,m.r)("yt.www.watch.activity.setTimestamp",m.yq);
(0,m.r)("yt.sharing.facebooktokenrefresh.finish",function(a){var b={session_token:(0,m.Lc)("social_connector_ajax"),service:"facebook"},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);(0,m.V)("/social_connector_ajax",{method:"POST",format:"JSON",ha:{action_connect_service:1},ga:b})});
(0,m.Ga)((0,m.Gc)({name:"www/watch",deps:["www/common"],page:"watch",init:function(){eE();zF();MD();IF.push((0,m.x)("ypc-purchase-success",HF));(0,m.Ou)();(0,m.t)("FACEBOOK_TOKEN_REFRESH_ENABLED")&&$C();var a=(0,m.t)("WATCH_REFRESH_TIMEOUT");a&&(0,m.u)(function(){window.location.reload(!0)},a)},dispose:function(){AF&&(AF.destroy(),AF=null);BF&&(BF.destroy(),BF=null);(0,m.Tf)(window.document,"keypress",m.wq);(0,m.Tf)(window.document,"click",m.xq);m.vq=-2;(0,m.Tf)(window.document,"keypress",HB);null!=
window.adModuleLoaded&&(0,m.Hc)("adModuleLoaded");(0,m.w)(EC);bC&&(bC.removeEventListener("onApiChange",FC),bC=null);ZB&&(ZB.dispose(),ZB=null);OC=[];PC=[];MC=KC=!1;aC=oC=nC=mC=null;NC=eC=DC=!1;if(lC){for(var a=lC.length-1;0<=a;a--)(0,m.Hc)(lC[a]);lC=[]}IC();(0,m.Cx)();(0,m.Lq)(0);(0,m.S)(TB);TB.length=0;if((a=(0,m.Qq)())&&a.getApiInterface){a.removeEventListener("onCueRangeEnter",oB);a.removeEventListener("onReady",GB);for(var b=5;0<b;b--)a.removeCueRange("NEAR_END"+b)}(0,m.Da)(UB);UB.length=0;m.Pq&&
(0,m.pf)(m.Pq,"scrolled");m.Oq=null;m.Cq=m.Jq=m.Nq=!1;m.Dq=iB=m.Eq=AB=CB=fB=m.Bq=m.Pq=null;gB="";m.Hq=!1;m.Kq&&((0,m.w)(m.Kq),m.Kq=null);(a=(0,m.J)("guide-container"))&&(0,m.I)(a,"branded");if(a=(0,m.J)("player"))a.style.background="";DF&&((0,m.S)(DF),DF=[]);yF=!1;(0,m.Da)(EF);EF.length=0;(0,m.S)(FF);FF.length=0;(0,m.Da)(CF);CF.length=0;$D();(0,m.Da)(IF)}}));})(_yt_www);
